---
- git:
    repo: git@github.com:FunTimeCoding/shell-skeleton.git
    dest: '{{ ansible_user_dir }}/src/shell-skeleton'
  when: git.protocol == 'ssh'

- git:
    repo: https://github.com/FunTimeCoding/shell-skeleton.git
    dest: '{{ ansible_user_dir }}/src/shell-skeleton'
  when: git.protocol == 'https'

- file:
    path: '{{ ansible_user_dir }}/src/shell-skeleton/tmp'
    state: directory

- template:
    src: ethernet-device-linux.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/ethernet-device.txt'
  when: ansible_system == 'Linux'

- template:
    src: ethernet-device-macos.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/ethernet-device.txt'
  when: ansible_system == 'Darwin'

- template:
    src: domain-linux.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/domain.txt'
  when: ansible_system == 'Linux'

- template:
    src: domain-macos.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/domain.txt'
  when: ansible_system == 'Darwin'
