---
- git:
    repo: git@github.com:FunTimeCoding/shell-skeleton.git
    dest: '{{ ansible_user_dir }}/src/shell-skeleton'
  when: git.protocol == 'ssh'

- git:
    repo: https://github.com/FunTimeCoding/shell-skeleton.git
    dest: '{{ ansible_user_dir }}/src/shell-skeleton'
  when: git.protocol == 'https'

- file:
    path: '{{ ansible_user_dir }}/src/shell-skeleton/tmp'
    state: directory

- template:
    src: ethernet-device.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/ethernet-device.txt'

- template:
    src: domain.txt
    dest: '{{ ansible_user_dir }}/src/shell-skeleton/tmp/domain.txt'
